### ISSUE TITLE
always returns false

### ISSUE THREAD

**Issue by lain-d** [Aldaviva/lock-your-windows#3]
Trying this with windows 10 and it always returns false for me.

**Comment by Aldaviva** [comment]
Interesting, thanks for reporting this.

I am currently traveling for the holidays and don't have access to my development environment, but I will try to take a look at this once I am back.

**Comment by Aldaviva** [comment]
I very much forgot about this, sorry.
I just tested the new 0.0.1 version and `isLocked()` successfully returns `true` for me when (and only when) my Windows 10 computer is locked. This makes me think it's fixed in 0.0.1.
If this still breaks for anyone in 0.0.1, this can be reopened.
